kind: pipeline
type: docker
name: default

pipeline:
  build:
    image: node:14-buster-slim
    commands:
      - npm install
  publish:
    image: plugins/docker
    repo: registry.nerdcave.us/house/octopusenergy-consumption-metrics
    tags:
      - latest
      - ${DRONE_COMMIT_SHA}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    secrets:
      - source: REGISTRY_USERNAME
        target: docker_username
      - source: REGISTRY_PASSWORD
        target: docker_password
    when:
      branch: master