kind: pipeline
type: docker
name: default

pipeline:
  build:
    image: node:14-buster-slim
    commands:
      - npm install
  publish:
    image: plugins/docker
    repo: registry.nerdcave.us/home/octopusenergy-consumption-metrics
    tags:
      - latest
      - ${DRONE_COMMIT_SHA}
    username: ${REGISTRY_USERNAME}
    password: ${REGISTRY_PASSWORD}
    when:
      branch: master