kind: pipeline
type: docker
name: default

pipeline:
  build:
    image: node:14-buster-slim
    commands:
      - npm install
  publish:
    image: plugins/docker
    registry: registry.nerdcave.us
    repo: registry.nerdcave.us/house/octopusenergy-consumption-metrics
    tags:
      - latest
      - ${DRONE_COMMIT_SHA}
    username:
      from_secret: REGISTRY_USERNAME
    password:
      from_secret: REGISTRY_PASSWORD
    when:
      branch: master